# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1THqqmX7OIuxD3sWTiuYJVOcBGCIGG3m7
"""

from IPython.core.display import display, HTML
html_content = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Landing Page</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            line-height: 1.6;
            color: #333;
        }
        .navbar {
            display: flex;
            justify-content: space-between;
            align-items: center;
            background: #333;
            color: #fff;
            padding: 1rem 2rem;
        }
        .logo {
            font-size: 1.5rem;
            font-weight: bold;
        }
        .nav-links {
            list-style: none;
            display: flex;
            gap: 1.5rem;
        }
        .nav-links li a {
            color: #fff;
            text-decoration: none;
            font-weight: bold;
            transition: color 0.3s;
        }
        .nav-links li a:hover {
            color: #f4a261;
        }
        .hero {
            background: #f4a261;
            color: white;
            text-align: center;
            padding: 4rem 2rem;
        }
        .hero h1 {
            font-size: 2.5rem;
        }
        .hero button {
            padding: 0.5rem 1rem;
            background: #333;
            color: white;
            border: none;
            cursor: pointer;
            font-size: 1rem;
            transition: background 0.3s;
        }
        .hero button:hover {
            background: #2a9d8f;
        }
        .body-section {
            padding: 2rem;
            text-align: center;
        }
        .body-section h2 {
            margin-bottom: 1rem;
            color: #2a9d8f;
        }
        footer {
            background: #333;
            color: white;
            text-align: center;
            padding: 1rem 0;
        }
    </style>
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="logo">MyWebsite</div>
            <ul class="nav-links">
                <li><a href="#home">Home</a></li>
                <li><a href="#about">About</a></li>
                <li><a href="#services">Services</a></li>
                <li><a href="#contact">Contact</a></li>
            </ul>
        </nav>
    </header>
    <section id="home" class="hero">
        <h1>Welcome to My Website</h1>
        <p>Your one-stop solution for amazing services.</p>
        <button>Get Started</button>
    </section>
    <section id="about" class="body-section">
        <h2>About Us</h2>
        <p>We are dedicated to providing top-notch services to our clients with a focus on quality and excellence.</p>
    </section>
    <section id="services" class="body-section">
        <h2>Our Services</h2>
        <p>Explore a variety of services designed to meet your needs.</p>
    </section>
    <section id="contact" class="body-section">
        <h2>Contact Us</h2>
        <p>Have questions? Reach out to us!</p>
    </section>
    <footer>
        <p>&copy; 2024 MyWebsite. All rights reserved.</p>
    </footer>
</body>
</html>
"""
display(HTML(html_content))